<?php

/**
 * @file
 * Contains first.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function first_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the first module.
    case 'help.page.first':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hey Dude! Whatsssssupp!') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function first_theme()
{
  return [
    'first' => [
      'render element' => 'children',
    ],
  ];
}
